---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hardware
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: tink-system
    server: https://kubernetes.default.svc
  project: default
  #project: tinkerbell
  source:
    path: config/management/hardware
    repoURL: https://github.com/turtacn/bm-k8s.git
    targetRevision: HEAD
