---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload-apps
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  destination:
    namespace: argo-cd
    server: https://kubernetes.default.svc
  project: default
  #project: workload
  source:
    repoURL: 'https://github.com/turtacn/bm-k8s.git'
    path: applications/workload
    targetRevision: HEAD
