---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevirt-vncproxy
spec:
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
  destination:
    namespace: kube-system
    server: https://10.100.3.140:6443
  project: workload
  source:
    path: config/workload/kubevirt-vnc
    repoURL: https://github.com/turtacn/bm-k8s.git
    targetRevision: HEAD
